# Generated by Django 2.0.4 on 2018-04-04 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.CharField(max_length=10)),
                ('model', models.CharField(max_length=10)),
                ('avto_id', models.IntegerField()),
            ],
        ),
    ]
